kind: Deployment
apiVersion: apps/v1
metadata:
  name: adapter
  namespace: default
  labels:
    app.kubernetes.io/instance: adapter
    app.kubernetes.io/name: adapter
    app.kubernetes.io/version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: adapter
      app.kubernetes.io/name: adapter
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: adapter
        app.kubernetes.io/name: adapter
    spec:
      containers:
        - name: adapter
          image: dockerhub.com/cjx/adapter:1.0.0
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: adapter
  namespace: default
  labels:
    app.kubernetes.io/instance: adapter
    app.kubernetes.io/name: adapter
    app.kubernetes.io/version: 1.0.0
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
      nodePort: 30080
  selector:
    app.kubernetes.io/instance: adapter
    app.kubernetes.io/name: adapter
  type: NodePort